# ----------------------------------------------------------------------------
#
# Package             : zm-db-conf
# Source Repo         : https://github.com/Zimbra/zm-db-conf
# Travis Job Link     : https://travis-ci.com/github/asellappen/zm-db-conf/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: bash

arch:
    - amd64
    - ppc64le
    
install :
  - sudo apt install m4 libpcre3-dev
  
script :
  - cd zimbra/apache-base
  - make build
  - make all
  - ls -ltr build/UBUNTU16_64/
